[project]
name = "hass-teleco-daisy"
version = "0.2.1"
description = "Home Assistant custom component for Teleco Automation Daisy"
readme = "README.md"
requires-python = ">=3.14"
# ! REMEMBER the manifest.json
dependencies = [
    "aiohttp>=3.8",
    "pydantic>=2.0",
]

[dependency-groups]
dev = [
    "homeassistant>=2026",
    "ruff>=0.15",
]
